In [6]:
import numpy as np
import cv2

In [19]:
# create matrix of zeroes 
a = np.zeros((3,3))
a

In [20]:
# create matrix of ones
b = np.ones((3,3))
b

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [33]:
# create matrix with specific values
c = np.array((1))
d = np.array((2))
e = np.array(((1,2,3),(4,5,6)))
e

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
# matrix addition 
f = np.array(((1,2,3),(4,5,6)))
g = np.ones((2,3))
h = f + g
h

array([[ 2.,  3.,  4.],
       [ 5.,  6.,  7.]])

In [36]:
# matrix subtration
i = f - g
i

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.]])

In [48]:
# matrix mulitplication
# matrix produt
j = f * f
j

m1 = np.array(((1,2,3),(4,5,6))) # 2x3
m2 = np.array(((7,8),(9,10),(11,12)))# 3X2
m3 = np.dot(m1,m2)
m3

array([[ 58,  64],
       [139, 154]])

In [41]:
# matrix division
k = f/f
k

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [ ]:
# vector mulitplication
l = np.array(())